=== antoninkrotky/dirigent/dirigent/resources/patterns/dirigent-pattern.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/dirigent-pattern/" targetNamespace="http://www.example.org/dirigent-pattern/">
    <complexType name="Pattern">
    	<sequence>
    		<element name="Documentation" type="string"></element>
    		<element name="Parameter" type="tns:Parameter"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="PatternStep" type="tns:PatternStep"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>

    	</sequence>

    	<attribute name="name" type="string"></attribute>
    </complexType>

    <element name="Pattern" type="tns:Pattern"></element>

    <complexType name="PatternStep">
    	<sequence>
            <element name="Documentation" type="string" maxOccurs="1" minOccurs="0">
    		</element>
            <element name="Parameter" type="tns:StepParameter" maxOccurs="unbounded" minOccurs="0"></element>
    		<element name="Template" type="string"></element>

    	</sequence>
    	<attribute name="name" type="string"></attribute>
    	<attribute name="type" type="tns:PatternStepType"
    		default="File">
    	</attribute>
    	<attribute name="condition" type="string"></attribute>
    	<attribute name="ignoreErrors" type="boolean" default="false"></attribute>
    </complexType>

    <complexType name="Parameter">
    	<sequence>
    		<element name="Documentation" type="string"></element>
    	</sequence>
    	<attribute name="name" type="string"></attribute>
    	<attribute name="defaultValue" type="string"></attribute>
     </complexType>

    <simpleType name="PatternStepType">
    	<restriction base="string">
    		<enumeration value="File"></enumeration>
    		<enumeration value="JDBCStatement"></enumeration>
    	</restriction>
    </simpleType>


    <complexType name="StepParameter">
    	<attribute name="name" type="string"></attribute>
    	<attribute name="value" type="string"></attribute>
    </complexType>
</schema>

=== antoninkrotky/dirigent/dirigent/resources/patterns/ORACLE/FACT_LOAD.pattern.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Pattern xmlns:tns="http://www.example.org/dirigent-pattern/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/dirigent-pattern/ ../dirigent-pattern.xsd ">
	<Documentation>TODO</Documentation>

	<PatternStep ignoreErrors="true" name="Drop Stage Table" type="JDBCStatement">
		<Template><![CDATA[    
		DROP TABLE STG_${element.targetTable.name}
    ]]>
    </Template>
	</PatternStep>

	<PatternStep name="Create Stage Table" type="JDBCStatement">
		<Template><![CDATA[    
		CREATE TABLE STG_${element.targetTable.name}
		(
			${element.targetColumnList}
		)
		as
		${element.SQLQuery}
    ]]>
    </Template>
	</PatternStep>
	
	<PatternStep name="Merge" type="JDBCStatement">
		<Template><![CDATA[ 
		INSERT INTO ${element.targetTable.name}
		(
			${element.targetColumnList},
			${element.targetTable.alias}_KEY
    	)
	    	SELECT 
	    		${element.targetColumnList},
	    		${element.targetTable.alias}_SEQ.NEXTVAL
			FROM STG_${element.targetTable.name} stg
    ]]>
    </Template>
	</PatternStep>
</tns:Pattern>

=== antoninkrotky/dirigent/dirigent/resources/patterns/HSQL/TRUNCATE_INSERT_JDBC.pattern.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Pattern xmlns:tns="http://www.example.org/dirigent-pattern/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/dirigent-pattern/ ../dirigent-pattern.xsd"
	name="TRUNCATE_INSERT">
	<Documentation> Load target table using truncate insert pattern. 
	</Documentation>
	<Parameter name="truncateTargetTable" defaultValue="Yes">
		<Documentation>If Yes target table will be truncated before loading
			data.</Documentation>
	</Parameter>
	<PatternStep name="Truncate target table" type="JDBCStatement">
		<Template> DELETE FROM ${element.targetTable.fullName};</Template>
	</PatternStep>
	<PatternStep name="Load target table" type="JDBCStatement">
		<Template> INSERT INTO ${element.targetTable.fullName}
			(${element.targetColumnList}) ${element.SQLQuery};</Template>
	</PatternStep>
</tns:Pattern>

=== antoninkrotky/dirigent/trunk/dirigent/resources/patterns/ORACLE/DIMENSION_CREATE.pattern.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Pattern name="" xmlns:tns="http://www.example.org/dirigent-pattern/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/dirigent-pattern/ ../dirigent-pattern.xsd ">
  <Documentation>Documentation</Documentation>
  <Parameter defaultValue="" name="">
    <Documentation>Documentation</Documentation>
  </Parameter>
    <PatternStep ignoreErrors="false" name="DropTable" type="File">
    <Parameter name="fileName" value="data-model/L2/${element.name}.sql"/>
    <Parameter name="fileName" value="overwrite"/>
    <Template><![CDATA[    

    /*Drop dimension table and ignore errors.*/
    begin
    	EXECUTE IMMEDIATE 'DROP TABLE ${element.name}'
    exception
    	when others then
    		null;
    end;   

    /*Create dimension table*/  
    CREATE TABLE ${element.name} (
    ${element.targetTable.codeName}_KEY NUMBER(38) PRIMARY KEY
    --Add missing columns here.
   
    /*Drop sequence.*/
    begin
    	EXECUTE IMMEDIATE 'DROP SEQUENCE ${element.codeName}_SEQ';
    exception
    	when others then
    		null;
    end;   
   
	/*Create sequence for generation of surrogate key values.*/   
    CREATE SEQUENCE ${element.codeName}_SEQ;
    ]]>
    </Template>
  </PatternStep>
</tns:Pattern>

=== antoninkrotky/dirigent/dirigent/resources/patterns/HSQL/DIMENSION_TRUNCATE_INSERT_JDBC.pattern.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Pattern xmlns:tns="http://www.example.org/dirigent-pattern/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/dirigent-pattern/ ../dirigent-pattern.xsd"
	name="DIMENSION_TRUNCATE_INSERT_JDBC">
	<Documentation> Load target table using truncate insert pattern. 
	</Documentation>
	<Parameter name="truncateTargetTable" defaultValue="Yes">
		<Documentation>If Yes target table will be truncated before loading
			data.</Documentation>
	</Parameter>
	<PatternStep name="Drop target table" type="JDBCStatement"
		ignoreErrors="true">
		<Template> DROP TABLE ${element.targetTable.fullName};</Template>
	</PatternStep>
	<PatternStep name="Create target table" type="JDBCStatement">
		<Template> CREATE TABLE ${element.targetTable.fullName} (
		${element.targetTable.codeName}_KEY INTEGER GENERATED BY DEFAULT AS IDENTITY,
		#foreach ($column in $element.targetTable.columns)
			$column.name $column.dataType,			
		#end
		CREATED_TS TIMESTAMP default CURRENT_TIMESTAMP,
		UPDATED_TS TIMESTAMP default CURRENT_TIMESTAMP
		);
		</Template>
	</PatternStep>
	<PatternStep name="Load target table" type="JDBCStatement">
		<Template> INSERT INTO ${element.targetTable.fullName}
			(${element.targetColumnList}) ${element.SQLQuery};</Template>
	</PatternStep>
</tns:Pattern>

=== antoninkrotky/dirigent/dirigent/resources/patterns/ORACLE/FACT_CREATE.pattern.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Pattern xmlns:tns="http://www.example.org/dirigent-pattern/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/dirigent-pattern/ ../dirigent-pattern.xsd ">
	<Documentation>TODO</Documentation>
  
	<PatternStep ignoreErrors="false" name="DropObjects" type="File">
		<Parameter name="fileName" value="data-model/L2/${element.name}.drop.sql" />
		<Parameter name="mode" value="overwrite" />
		<Template><![CDATA[    
	   	/*Drop script for fact table ${element.name}*/
	
	   	/*Drop table.*/
	   	DROP TABLE ${element.name};		
	   ]]>
	   </Template>
	</PatternStep>
	<PatternStep ignoreErrors="false" name="CreateObjects"
		type="File">
		<Parameter name="fileName" value="data-model/L2/${element.name}.create.sql" />
		<Parameter name="mode" value="overwrite" />
		<Template><![CDATA[    
	   	/*Create script for fact table ${element.name}*/  
	   	CREATE TABLE ${element.name} (
	   		#foreach($column in $element.columns)${column.name} ${column.dataType},
    		#end
    		
    		#set($comma=false)
    		#foreach($dim in $element.relatedDimensions)
    			#if ($comma),#else#set($comma=true)#end
    			${dim.alias}_KEY INTEGER
    		#end
	   	);
	   	
	   	${element.relatedDimensions}
	   	
   		#foreach($dim in $element.relatedDimensions)
   			ALTER TABLE ${element.name} ADD CONSTRAINT FK_${element.alias}_${dim.alias}
   			FOREIGN KEY (${dim.alias}_KEY) REFERENCES ${dim.name}(${dim.alias}_KEY) DISABLE
   		#end
	   ]]>
	   </Template>
	</PatternStep>
</tns:Pattern>

=== antoninkrotky/dirigent/dirigent/resources/patterns/HSQL/DIMENSION_CREATE_JDBC.pattern.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Pattern xmlns:tns="http://www.example.org/dirigent-pattern/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/dirigent-pattern/ ../dirigent-pattern.xsd"
	name="DIMENSION_TRUNCATE_INSERT_JDBC">
	<Documentation> Load target table using truncate insert pattern. 
	</Documentation>
	<Parameter name="truncateTargetTable" defaultValue="Yes">
		<Documentation>If Yes target table will be truncated before loading
			data.</Documentation>
	</Parameter>
	<PatternStep name="Drop target table" type="JDBCStatement"
		ignoreErrors="true">
		<Template> DROP TABLE ${element.fullName};</Template>
	</PatternStep>
	<PatternStep name="Create target table" type="JDBCStatement">
		<Template> CREATE TABLE ${element.fullName} (
		${element.codeName}_KEY INTEGER GENERATED BY DEFAULT AS IDENTITY,
		#foreach ($column in $element.columns)
			$column.name $column.dataType,			
		#end
		CREATED_TS TIMESTAMP default CURRENT_TIMESTAMP,
		UPDATED_TS TIMESTAMP default CURRENT_TIMESTAMP
		);
		</Template>
	</PatternStep>
</tns:Pattern>

=== antoninkrotky/dirigent/dirigent/resources/patterns/TEST/TEST_FILE_EXECUTOR.pattern.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Pattern xmlns:tns="http://www.example.org/dirigent-pattern/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/dirigent-pattern/ ../dirigent-pattern.xsd ">
	<Documentation>Pattern for performing unit test on FileExecutor.</Documentation>
	<PatternStep name="TestAppend" type="File">
		<Parameter name="fileName" value="test/Append.txt" />
		<Parameter name="mode" value="append" />
		<Template> This text was appended by Dirigent. </Template>
	</PatternStep>
	<PatternStep name="TestOverwrite" type="File">
		<Parameter name="fileName" value="test/Overwrite.txt" />
		<Parameter name="mode" value="overwrite" />
		<Template> This text was appended by Dirigent. </Template>
	</PatternStep>
	<PatternStep name="TestCreate" type="File">
		<Parameter name="fileName" value="test/Create.txt" />
		<Parameter name="mode" value="create" />
		<Template> This text was generated by Dirigent. </Template>
	</PatternStep>
		<PatternStep name="TestConfig" type="File">
		<Parameter name="fileName" value="test/Config.txt" />
		<Parameter name="mode" value="overwrite" />
		<Template> dirigent.model.path=${config.getProperty("dirigent.model.path")} </Template>
	</PatternStep>
</tns:Pattern>

=== antoninkrotky/dirigent/trunk/dirigent/resources/patterns/HSQL/TRUNCATE_INSERT_JDBC.pattern.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Pattern xmlns:tns="http://www.example.org/dirigent-pattern/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/dirigent-pattern/ ../dirigent-pattern.xsd" name="TRUNCATE_INSERT">
	<Documentation> Load target table using truncate insert pattern. 
	</Documentation>
	<Parameter name="TruncateTargetTable" defaultValue="Yes">
		<Documentation>If Yes target table will be truncated before loading
			data.</Documentation>
	</Parameter>
	<Parameter name="CreateTargetTable" defaultValue="No">
		<Documentation>If Yes target table will be created before loading
			data. Table will not be dropped if exists.</Documentation>
	</Parameter>
	<PatternStep name="Create target table" type="JDBCStatement">
		<Template> --Not implemented as HSQL does not support CREATE TABLE AS SELECT.</Template>
	</PatternStep>
	<PatternStep name="Truncate target table" type="JDBCStatement">
		<Template> DELETE FROM ${element.targetTable.fullName};</Template>
	</PatternStep>
	<PatternStep name="Load target table" type="JDBCStatement">
		<Template> INSERT INTO ${element.targetTable.fullName}
			${element.SQLQuery};</Template>
	</PatternStep>
</tns:Pattern>
