=== antoninkrotky/dirigent/dirigent/resources/patterns/dirigent-pattern.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/dirigent-pattern/" targetNamespace="http://www.example.org/dirigent-pattern/">
    <complexType name="Pattern">
    	<sequence>
    		<element name="Documentation" type="string"></element>
    		<element name="Parameter" type="tns:Parameter"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="PatternStep" type="tns:PatternStep"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>

    	</sequence>

    	<attribute name="name" type="string"></attribute>
    </complexType>

    <element name="Pattern" type="tns:Pattern"></element>

    <complexType name="PatternStep">
    	<sequence>
            <element name="Documentation" type="string" maxOccurs="1" minOccurs="0">
    		</element>
            <element name="Parameter" type="tns:StepParameter" maxOccurs="unbounded" minOccurs="0"></element>
    		<element name="Template" type="string"></element>

    	</sequence>
    	<attribute name="name" type="string"></attribute>
    	<attribute name="type" type="tns:PatternStepType"
    		default="File">
    	</attribute>
    	<attribute name="condition" type="string"></attribute>
    	<attribute name="ignoreErrors" type="boolean" default="false"></attribute>
    </complexType>

    <complexType name="Parameter">
    	<sequence>
    		<element name="Documentation" type="string"></element>
    	</sequence>
    	<attribute name="name" type="string"></attribute>
    	<attribute name="defaultValue" type="string"></attribute>
     </complexType>

    <simpleType name="PatternStepType">
    	<restriction base="string">
    		<enumeration value="File"></enumeration>
    		<enumeration value="JDBCStatement"></enumeration>
    	</restriction>
    </simpleType>


    <complexType name="StepParameter">
    	<attribute name="name" type="string"></attribute>
    	<attribute name="value" type="string"></attribute>
    </complexType>
</schema>

=== antoninkrotky/dirigent/dirigent/resources/patterns/ORACLE/DIMENSION_CREATE.pattern.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Pattern name="" xmlns:tns="http://www.example.org/dirigent-pattern/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/dirigent-pattern/ ../dirigent-pattern.xsd ">
	<Documentation>Documentation</Documentation>
	<PatternStep ignoreErrors="false" name="DropObjects" type="File">
		<Parameter name="fileName" value="data-model/L2/${element.name}.drop.sql" />
		<Parameter name="mode" value="overwrite" />
		<Template><![CDATA[    
    	/*Drop script for dimension ${element.name}*/

    	/*Drop table.*/
    	DROP TABLE ${element.name};

    	/*Drop sequence.*/
		DROP SEQUENCE ${element.alias}_SEQ;		
    ]]>
    </Template>
	</PatternStep>
	<PatternStep ignoreErrors="false" name="CreateObjects"
		type="File">
		<Parameter name="fileName" value="data-model/L2/${element.name}.create.sql" />
		<Parameter name="mode" value="overwrite" />
		<Template><![CDATA[    
    	/*Create script for dimension ${element.name}*/  
    	CREATE TABLE ${element.name} (
    		${element.alias}_KEY NUMBER(38) PRIMARY KEY,
    		#foreach($column in $element.columns)${column.name} ${column.dataType},
    		#end		
			
			${element.alias}_VALID_FROM_DATETIME DATE,
			${element.alias}_VALID_TO_DATETIME DATE,
			${element.alias}_CURRENT_FLAG CHAR(1),
			${element.alias}_UPDATED_DATETIME DATE
    	);

		/*Create sequence for generation of surrogate key values.*/   
    	CREATE SEQUENCE ${element.alias}_SEQ;
    ]]>
    </Template>
	</PatternStep>
</tns:Pattern>

=== antoninkrotky/dirigent/trunk/dirigent/resources/patterns/ORACLE/FACT_LOAD.pattern.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Pattern xmlns:tns="http://www.example.org/dirigent-pattern/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/dirigent-pattern/ ../dirigent-pattern.xsd ">
	<Documentation>TODO</Documentation>

	<PatternStep ignoreErrors="true" name="Drop Stage Table" type="File">
		<Parameter name="fileName" value="data-model/L2/${element.name}.factLoad.sql" />
		<Parameter name="mode" value="overwrite" />
		<Template><![CDATA[    
		DROP TABLE STG_${element.targetTable.name}
    ]]>
    </Template>
	</PatternStep>

	<PatternStep name="Create Stage Table" type="File">
	<Parameter name="fileName" value="data-model/L2/${element.name}.factLoad.sql" />
	<Parameter name="mode" value="append" />
		<Template><![CDATA[    
		CREATE TABLE STG_${element.targetTable.name}
		(
			${element.targetColumnList}
		)
		as
		${element.SQLQuery}
    ]]>
    </Template>
	</PatternStep>

	<PatternStep name="Dimension Lookup Update" type="File">
	<Parameter name="fileName" value="data-model/L2/${element.name}.factLoad.sql" />
	<Parameter name="mode" value="append" />
		<Template><![CDATA[
		#set( $naturalKeyProperty = "naturalKey" )
		    
		UPDATE ${element.targetTable.name} target
		SET
		#set($comma = false)
		#foreach( ${dim} in ${element.targetTable.relatedDimensions} )
			#if($comma),#else#set($comma = true)#end
			target.${dim.alias}_KEY = (
				SELECT d2.${dim.alias}_KEY 
				FROM ${dim.name} d1 JOIN ${dim.name} d2 ON (
					${utils.getWhereClausule(${dim.getColumnListBySCDType(${naturalKeyProperty})}, "=", "AND", "d1", "d2")}
				)
				WHERE d1.${dim.alias}_KEY = target.${dim.alias}_KEY AND d2.${dim.alias}_CURRENT_FLAG = 'Y'
			)
		#end
		WHERE EXISTS (
			SELECT *
			FROM ${element.targetTable.name} fact
				#set($i = 1)
				#set($res = "")
				#foreach( ${dim} in ${element.targetTable.relatedDimensions} )
					JOIN ${dim.name} d${i} ON (fact.${dim.alias}_KEY = d${i}.${dim.alias}_KEY)
					#set($res = ${utils.joinStrings(${res}, "d${i}.${dim.alias}_CURRENT_FLAG = 'N'", "OR")})
					#set($i = $i + 1)
				#end
			WHERE fact.${element.targetTable.alias}_KEY = target.${element.targetTable.alias}_KEY AND ($res)
		)
    ]]>
    </Template>
	</PatternStep>

	<PatternStep name="Merge" type="File">
	<Parameter name="fileName" value="data-model/L2/${element.name}.factLoad.sql" />
	<Parameter name="mode" value="append" />
		<Template><![CDATA[ 
	MERGE INTO ${element.targetTable.name} target
	USING
		(
		SELECT *
		FROM STG_${element.targetTable.name}
		MINUS
			(
			SELECT ${element.targetColumnList}
			FROM ${element.targetTable.fullName}
			)
		) stage
	ON
		(
			#set($res = "")
			#foreach( ${dim} in ${element.targetTable.relatedDimensions} )
				#set($res = ${utils.joinStrings($res, "target.${dim.alias}_KEY = stage.${dim.alias}_KEY", " AND ")})
			#end
			${res}
			#*${utils.getWhereClausule(${element.targetTable.relatedDimensionsColumn}, "=", "AND", "target", "stage")}*#
		)
	WHEN MATCHED THEN
		UPDATE
		SET
		${utils.getWhereClausule(${element.targetTable.columns}, "=", ",", "target", "stage")}
		
	WHEN NOT MATCHED THEN
		INSERT
		(
			${element.targetColumnList},
			${element.targetTable.alias}_KEY
    	)
    	VALUES
    	(
    		#set($res = "")
    		#foreach( ${col} in ${element.columnMappings} )#set($res = ${utils.joinStrings(${res}, "stage.${col.column.name}", ",")})#end
    		
			#*
			#foreach( ${column} in ${element.targetTable.columns} )#set($res = ${utils.joinStrings(${res}, "stage.${column.name}", ",")})#end
			#foreach( ${column} in ${element.targetTable.relatedDimensions} )#set($res = ${utils.joinStrings(${res}, "stage.${column.alias}_KEY", ",")})#end
			*#
			#set($res = ${utils.joinStrings(${res}, "${element.targetTable.alias}_SEQ.NEXTVAL", ",")})
			$res
    	)
    ]]>
    </Template>
	</PatternStep>
</tns:Pattern>

=== antoninkrotky/dirigent/dirigent/resources/patterns/DIRIGENT/METAFACADE.pattern.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Pattern xmlns:tns="http://www.example.org/dirigent-pattern/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/dirigent-pattern/ ../dirigent-pattern.xsd ">
  <Documentation>Documentation</Documentation>
  <PatternStep ignoreErrors="false" name="Metafacade-Interface"
		type="File">
		<Parameter name="fileName" value="src/org/dirigent/metafacade/I${element.name}.java" />
		<Parameter name="mode" value="overwrite" />
		<Template>#parse("/patterns/DIRIGENT/IMetafacade.vm")</Template>
	</PatternStep>
	  <PatternStep ignoreErrors="false" name="Metafacade-Abstract-parent"
		type="File">
		<Parameter name="fileName" value="src/org/dirigent/metafacade/impl/Abstract${element.name}.java" />
		<Parameter name="mode" value="overwrite" />
		<Template>#parse("/patterns/DIRIGENT/AbstractMetafacade.vm")</Template>
	</PatternStep>
	  <PatternStep ignoreErrors="false" name="Metafacade-default-implementation"
		type="File">
		<Parameter name="fileName" value="src/org/dirigent/metafacade/impl/${element.name}Impl.java" />
		<Parameter name="mode" value="create" />
		<Template>#parse("/patterns/DIRIGENT/MetafacadeImpl.vm")</Template>
	</PatternStep>
</tns:Pattern>

=== antoninkrotky/dirigent/dirigent/resources/patterns/ORACLE/SCD_LOAD.pattern.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Pattern name="" xmlns:tns="http://www.example.org/dirigent-pattern/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/dirigent-pattern/ ../dirigent-pattern.xsd ">
	<Documentation>Documentation</Documentation>
	
	<PatternStep ignoreErrors="false" name="Drop Stage Table" type="File">
		<Parameter name="fileName" value="data-model/SCD/${element.name}.doscd.sql" />
		<Parameter name="mode" value="overwrite" />
		<Template><![CDATA[    
		DROP TABLE STG_${element.targetTable.name};
    ]]>
    </Template>
	</PatternStep>
	
	<PatternStep ignoreErrors="false" name="Create Stage Table" type="File">
		<Parameter name="fileName" value="data-model/SCD/${element.name}.doscd.sql" />
		<Parameter name="mode" value="append" />
		<Template><![CDATA[    
		CREATE TABLE STG_STG_${element.targetTable.name}
		(
			${element.targetColumnList}
		)
		as
		${element.SQLQuery};
    ]]>
    </Template>
	</PatternStep>
	
	<PatternStep ignoreErrors="false" name="CreateObjects"
		type="File">
		<Parameter name="fileName" value="data-model/SCD/${element.name}.doscd.sql" />
		<Parameter name="mode" value="append" />
		<Template><![CDATA[    
INSERT INTO ${element.targetTable.fullName} 
	(${element.targetColumnList},
    	CUST_VALID_FROM_DATETIME,
		CUST_VALID_TO_DATETIME,
		CUST_CURRENT_FLAG,
		CUST_UPDATED_DATETIME
    ) 
    values
    (
   		stage.*,
   		sysdate,
   		to_date('1.1.3000','dd.mm.yyyy'),
   		'Y',
   		sysdate
   		from STG_${element.targetTable.name} stage
   		/* todo where clausule */
   	);
    ]]>
    </Template>
	</PatternStep>
</tns:Pattern>

=== antoninkrotky/dirigent/dirigent/resources/patterns/DOCBOOK/Diagram.pattern.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Pattern xmlns:tns="http://www.example.org/dirigent-pattern/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/dirigent-pattern/ ../dirigent-pattern.xsd ">
	<Documentation>Documentation</Documentation>
	<PatternStep type="File" name="GenerateSection">
		<Parameter name="fileName" value="src/E${utils.removeBrackets($element.uri)}.xml" />
		<Parameter name="mode" value="overwrite" />
		<Template>#parse("/patterns/DOCBOOK/Diagram.vm")</Template>
	</PatternStep>
	<PatternStep type="File" name="GenerateSection">
		<Parameter name="fileName" value="src/DocumentEntities.ent" />
		<Parameter name="mode" value="append" />
		<Template><![CDATA[<!ENTITY E${utils.removeBrackets($element.uri)} SYSTEM "E${utils.removeBrackets($element.uri)}.xml">]]></Template>
	</PatternStep>
</tns:Pattern>

=== antoninkrotky/dirigent/dirigent/resources/patterns/ORACLE/SCD_LOAD_TIME.pattern.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Pattern xmlns:tns="http://www.example.org/dirigent-pattern/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/dirigent-pattern/ ../dirigent-pattern.xsd " name="SCD_LOAD_TIME">
  <Documentation>TODO</Documentation>
	<PatternStep name="Drop stage current table" type="JDBCStatement" ignoreErrors="true">
		<Template> DROP TABLE STG_${element.targetTable.name}</Template>
	</PatternStep>
	<PatternStep name="Create stage current table" type="JDBCStatement">
		<Template> <![CDATA[
			CREATE TABLE STG_${element.targetTable.name} 
				(${element.targetColumnList}) as ${element.SQLQuery}
		]]>
		</Template>
	</PatternStep>	
		<PatternStep name="Truncate target table" type="JDBCStatement">
		<Template> <![CDATA[
			TRUNCATE TABLE ${element.targetTable.fullName}
		]]>
		</Template>
	</PatternStep>	
	<PatternStep name="Load target table" type="JDBCStatement">
		<Template><![CDATA[ 
INSERT INTO ${element.targetTable.fullName}
			(${element.targetColumnList},
			${element.targetTable.alias}_KEY,
			${element.targetTable.alias}_VALID_FROM_DATETIME,
			${element.targetTable.alias}_VALID_TO_DATETIME,
			${element.targetTable.alias}_CURRENT_FLAG,
			${element.targetTable.alias}_UPDATED_DATETIME
			) 
			select 
				sc.*,
				to_number(to_char(sc.TIME_ID,'J')),
				sysdate,
				to_date('1.1.3000','dd.mm.yyyy'),
				'Y',
				sysdate				
			from STG_${element.targetTable.name} sc
]]>			
</Template>
	</PatternStep>
</tns:Pattern>
